name: Run Opera DataHub Express

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "*/15 * * * *"

jobs:
  run-datahub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DataHub
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_FOLDER: ${{ secrets.EMAIL_FOLDER }}
          EMAIL_DELETE_AFTER_SUCCESS: ${{ secrets.EMAIL_DELETE_AFTER_SUCCESS }}
        run: |
          python -m src.app